# Generated by Django 4.2.1 on 2023-06-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_creature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokedex_creature',
            new_name='pokedex_creature_id',
        ),
    ]
