# Generated by Django 4.2.1 on 2023-06-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_creature', '0002_rename_pokedex_creature_pokemon_pokedex_creature_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokedex_creature_id',
            new_name='pokedex_creature',
        ),
    ]
