# Generated by Django 4.2.1 on 2023-06-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_creature', '0004_alter_pokedexcreature_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexcreature',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
